In [1]:
import numpy as np
import pandas as pd
import re
import shutil
import os
import unicodedata
import urllib3
import zipfile
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [2]:
# http = urllib3.PoolManager()

# url ='http://www.manythings.org/anki/kor-eng.zip'

filename = 'kor-eng.zip'

path = os.getcwd()

zipfilename = os.path.join(path, filename)

# with http.request('GET', url, preload_content=False) as r, open(zipfilename, 'wb') as out_file:       

#     shutil.copyfileobj(r, out_file)

with zipfile.ZipFile(zipfilename, 'r') as zip_ref:
  zip_ref.extractall(path)

In [3]:
lines = pd.read_csv('kor.txt', names=['en','ko'], sep='\t', index_col=False)
lines.shape

(3729, 2)

In [4]:
lines.en[0]='Say hello.'
lines.en[0]
lines.ko[0]='인사해.'
lines.ko[0]

'인사해.'

In [5]:
lines.ko = lines.ko.apply(lambda x: '\t '+x+' \n')
lines[0:1]

en          ko
0  Say hello.  \t 인사해. \n

In [6]:
# en & ko 글자 집합 구축
en_vocab = set()
for line in lines.en :
  for char in line:
    en_vocab.add(char)

#print(en_vocab)

ko_vocab = set()
for line in lines.ko :
  for char in line:
    ko_vocab.add(char)

#print(ko_vocab)

In [7]:
en_vocab_size = len(en_vocab)+1
ko_vocab_size = len(ko_vocab)+1
print(en_vocab_size)
print(ko_vocab_size)

75
915


In [8]:
en_vocab = sorted(list(en_vocab))
ko_vocab = sorted(list(ko_vocab))
print(en_vocab)
print(ko_vocab)

[' ', '!', '"', '$', '%', "'", ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'Y', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '°', 'ï']
['\t', '\n', ' ', '!', '"', '%', '(', ')', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', '?', 'A', 'B', 'C', 'D', 'H', 'M', 'N', 'T', 'a', 'd', 'h', 'i', 'm', 'o', 'p', 'r', 't', 'y', '°', '가', '각', '간', '갇', '갈', '감', '갑', '값', '갔', '강', '갖', '같', '개', '객', '갰', '걀', '걔', '거', '걱', '건', '걷', '걸', '검', '겁', '것', '게', '겐', '겠', '겨', '격', '겪', '견', '결', '겼', '경', '계', '고', '곡', '곤', '곧', '골', '곰', '곱', '곳', '공', '과', '관', '광', '괜', '괴', '굉', '교', '구', '국', '군', '굳', '굴', '굶', '굼', '굽', '궁', '권', '귀', '귄', '규', '그', '극', '근', '글', '금', '급', '긋', '긍', '기', '긴', '길', '깊', '까', '깎', '깐', '깔', '깜', '

In [9]:
# char 별 idx 매칭
en_idx = dict([(word, i+1) for i, word in enumerate(en_vocab)])
ko_idx = dict([(word, i+1) for i, word in enumerate(ko_vocab)])

print(en_idx)
print(ko_idx)

{' ': 1, '!': 2, '"': 3, '$': 4, '%': 5, "'": 6, ',': 7, '-': 8, '.': 9, '0': 10, '1': 11, '2': 12, '3': 13, '4': 14, '5': 15, '6': 16, '7': 17, '8': 18, '9': 19, ':': 20, ';': 21, '?': 22, 'A': 23, 'B': 24, 'C': 25, 'D': 26, 'E': 27, 'F': 28, 'G': 29, 'H': 30, 'I': 31, 'J': 32, 'K': 33, 'L': 34, 'M': 35, 'N': 36, 'O': 37, 'P': 38, 'Q': 39, 'R': 40, 'S': 41, 'T': 42, 'U': 43, 'V': 44, 'W': 45, 'Y': 46, 'a': 47, 'b': 48, 'c': 49, 'd': 50, 'e': 51, 'f': 52, 'g': 53, 'h': 54, 'i': 55, 'j': 56, 'k': 57, 'l': 58, 'm': 59, 'n': 60, 'o': 61, 'p': 62, 'q': 63, 'r': 64, 's': 65, 't': 66, 'u': 67, 'v': 68, 'w': 69, 'x': 70, 'y': 71, 'z': 72, '°': 73, 'ï': 74}
{'\t': 1, '\n': 2, ' ': 3, '!': 4, '"': 5, '%': 6, '(': 7, ')': 8, ',': 9, '-': 10, '.': 11, '/': 12, '0': 13, '1': 14, '2': 15, '3': 16, '4': 17, '5': 18, '6': 19, '7': 20, '8': 21, '9': 22, ':': 23, '?': 24, 'A': 25, 'B': 26, 'C': 27, 'D': 28, 'H': 29, 'M': 30, 'N': 31, 'T': 32, 'a': 33, 'd': 34, 'h': 35, 'i': 36, 'm': 37, 'o': 38, 'p': 3

In [10]:
# 입력 구성
encoder_input = []
for line in lines.en :
  temp_X = []
  for w in line:
    temp_X.append(en_idx[w])   #char - int 변환
  encoder_input.append(temp_X)
print(encoder_input[:10])

[[41, 47, 71, 1, 54, 51, 58, 58, 61, 9], [30, 55, 9], [40, 67, 60, 2], [40, 67, 60, 9], [45, 54, 61, 22], [45, 61, 69, 2], [28, 55, 64, 51, 2], [30, 51, 58, 62, 2], [32, 67, 59, 62, 2], [32, 67, 59, 62, 9]]


In [11]:
# 출력 구성
decoder_input = []
for line in lines.ko :
  temp_X = []
  for w in line:
    temp_X.append(ko_idx[w])   #char - int 변환
  decoder_input.append(temp_X)
print(decoder_input[:10])

[[1, 3, 641, 472, 862, 11, 3, 2], [1, 3, 551, 195, 11, 3, 2], [1, 3, 289, 573, 4, 3, 2], [1, 3, 289, 573, 11, 3, 2], [1, 3, 206, 96, 24, 3, 2], [1, 3, 615, 606, 4, 3, 2], [1, 3, 539, 4, 3, 2], [1, 3, 243, 606, 690, 4, 3, 2], [1, 3, 666, 848, 4, 3, 2], [1, 3, 666, 848, 862, 11, 3, 2]]


In [12]:
# ko column 의 \t 제거
decoder_target = []
for line in lines.ko :
  t=0
  temp_X = []
  for w in line:
    if t>0:
      temp_X.append(ko_idx[w])
    t=t+1
  decoder_target.append(temp_X)
print(decoder_target[:10])

[[3, 641, 472, 862, 11, 3, 2], [3, 551, 195, 11, 3, 2], [3, 289, 573, 4, 3, 2], [3, 289, 573, 11, 3, 2], [3, 206, 96, 24, 3, 2], [3, 615, 606, 4, 3, 2], [3, 539, 4, 3, 2], [3, 243, 606, 690, 4, 3, 2], [3, 666, 848, 4, 3, 2], [3, 666, 848, 862, 11, 3, 2]]


In [13]:
# max length
max_en_len = max([len(line) for line in lines.en])
max_ko_len = max([len(line) for line in lines.ko])

print(max_en_len)
print(max_ko_len)

537
300


In [14]:
# 최대 길이를 10으로 나누어 사용 (학습 시간 단축)\n",
max_en_len //= 10
max_ko_len //= 10
print(max_en_len) 
print(max_ko_len)  
encoder_input = pad_sequences(encoder_input, maxlen=max_en_len, padding='post')
decoder_input = pad_sequences(decoder_input, maxlen=max_ko_len, padding='post')
decoder_target = pad_sequences(decoder_target, maxlen=max_ko_len, padding='post')

53
30


In [15]:
# 원핫 벡터
encoder_input = to_categorical(encoder_input)
decoder_input = to_categorical(decoder_input)
decoder_target = to_categorical(decoder_target)

# **seq2seq 모델** **구현**

In [17]:
from tensorflow.keras.layers import Input, LSTM, Embedding, Dense
from tensorflow.keras.models import Model

In [18]:
encoder_inputs = Input(shape=(None, en_vocab_size))
encoder_lstm = LSTM(units=2048, return_state=True)
encoder_outputs, state_h, state_c = encoder_lstm(encoder_inputs)
# encoder_outputs도 같이 리턴받기는 했지만 여기서는 필요없으므로 이 값은 버림.
encoder_states = [state_h, state_c] #은닉 상태, 셀 상태

In [19]:
decoder_inputs = Input(shape=(None, ko_vocab_size)) 
decoder_lstm = LSTM(units=2048, return_sequences=True, return_state=True)
decoder_outputs, _, _= decoder_lstm(decoder_inputs, initial_state=encoder_states)

decoder_softmax_layer = Dense(ko_vocab_size, activation='softmax')
decoder_outputs = decoder_softmax_layer(decoder_outputs)

#adams
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
model.compile(optimizer="adam", loss="categorical_crossentropy")
model.summary()

# embedding 계층 관련 학습!

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, None, 75)]   0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, None, 915)]  0                                            
__________________________________________________________________________________________________
lstm (LSTM)                     [(None, 2048), (None 17399808    input_1[0][0]                    
__________________________________________________________________________________________________
lstm_1 (LSTM)                   [(None, None, 2048), 24281088    input_2[0][0]                    
                                                                 lstm[0][1]                   

In [20]:
model.load_weights('./kopago_model.hdf5')

In [21]:
encoder_model = Model(inputs=encoder_inputs, outputs=encoder_states)
encoder_model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, None, 75)]        0         
_________________________________________________________________
lstm (LSTM)                  [(None, 2048), (None, 204 17399808  
Total params: 17,399,808
Trainable params: 17,399,808
Non-trainable params: 0
_________________________________________________________________


In [22]:
# 이전 시점의 상태들을 저장하는 텐서
decoder_state_input_h = Input(shape=(2048,))
decoder_state_input_c = Input(shape=(2048,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]
decoder_outputs, state_h, state_c = decoder_lstm(decoder_inputs, initial_state=decoder_states_inputs)
# 문장의 다음 단어를 예측하기 위해서 초기 상태(initial_state)를 이전 시점의 상태로 사용. 이는 뒤의 함수 decode_sequence()에 구현
decoder_states = [state_h, state_c]
# 훈련 과정에서와 달리 LSTM의 리턴하는 은닉 상태와 셀 상태인 state_h와 state_c를 버리지 않음.
decoder_outputs = decoder_softmax_layer(decoder_outputs)
decoder_model = Model(inputs=[decoder_inputs] + decoder_states_inputs, outputs=[decoder_outputs] + decoder_states)
decoder_model.summary()

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, None, 915)]  0                                            
__________________________________________________________________________________________________
input_3 (InputLayer)            [(None, 2048)]       0                                            
__________________________________________________________________________________________________
input_4 (InputLayer)            [(None, 2048)]       0                                            
__________________________________________________________________________________________________
lstm_1 (LSTM)                   [(None, None, 2048), 24281088    input_2[0][0]                    
                                                                 input_3[0][0]              

In [23]:
idx_to_en = dict((i, char) for char, i in en_idx.items())
idx_to_ko = dict((i, char) for char, i in ko_idx.items())

In [24]:
def decode_sequence(input_seq):
    # 입력으로부터 인코더의 상태를 얻음
    states_value = encoder_model.predict(input_seq)

    # <SOS>에 해당하는 원-핫 벡터 생성
    target_seq = np.zeros((1, 1, ko_vocab_size))
    target_seq[0, 0, ko_idx['\t']] = 1.

    stop_condition = False
    decoded_sentence = ""

    # stop_condition이 True가 될 때까지 루프 반복
    while not stop_condition:
        # 이점 시점의 상태 states_value를 현 시점의 초기 상태로 사용
        output_tokens, h, c = decoder_model.predict([target_seq] + states_value)

        # 예측 결과를 문자로 변환
        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        sampled_char = idx_to_ko[sampled_token_index]

        # 현재 시점의 예측 문자를 예측 문장에 추가
        decoded_sentence += sampled_char

        # <eos>에 도달하거나 최대 길이를 넘으면 중단.
        if (sampled_char == '\n' or
           len(decoded_sentence) > max_ko_len):
            stop_condition = True

        # 현재 시점의 예측 결과를 다음 시점의 입력으로 사용하기 위해 저장
        target_seq = np.zeros((1, 1, ko_vocab_size))
        target_seq[0, 0, sampled_token_index] = 1.

        # 현재 시점의 상태를 다음 시점의 상태로 사용하기 위해 저장
        states_value = [h, c]

    return decoded_sentence

In [27]:
for i in range(1): # 입력 문장의 인덱스
    seq_index = 0
    input_seq = encoder_input[seq_index: seq_index + 1]
    print(input_seq)
    print(len(input_seq[0]))
    print(len(input_seq[0][0]))
    decoded_sentence = decode_sequence(input_seq)
    print(35 * "-")
    print('입력 문장:', lines.en[0])
    print('정답 문장:', lines.ko[0][1:len(lines.ko[seq_index])-1]) # '\t'와 '\n'을 빼고 출력
    print('번역기가 번역한 문장:', decoded_sentence[:len(decoded_sentence)-1]) # '\n'을 빼고 출력

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]]
53
75
-----------------------------------
입력 문장: Say hello.
정답 문장:  인사해. 
번역기가 번역한 문장:  인사해. 
